In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
import pandas as pd
import numpy as np


In [9]:
df = pd.read_csv('/content/drive/MyDrive/price_data.csv')

In [10]:
df.head()

baseFare  reservationCharge  superfastCharge  fuelAmount  totalConcession  \
0      1059                 60                0         0.0                0   
1       626                 50                0         0.0                0   
2       441                 40                0         0.0                0   
3       125                 20                0         0.0                0   
4      1059                 60                0         0.0                0   

   tatkalFare  serviceTax  otherCharge  cateringCharge  dynamicFare  \
0           0        56.0            0               0            0   
1           0        34.0            0               0            0   
2           0        24.0            0               0            0   
3           0         0.0            0               0            0   
4           0        56.0            0               0            0   

   totalFare                                       availability  trainNumber  \
0       1175  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   
1        710  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   
2        505  [{'date': '2-12-2023', 'status': 'AVAILABLE-01...        11464   
3        145  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   
4       1175  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   

                    timeStamp fromStnCode toStnCode classCode  distance  \
0  2023-10-03 22:13:07.781307         JBP      SRID        1A        54   
1  2023-10-03 22:13:07.781307         JBP      SRID        2A        54   
2  2023-10-03 22:13:07.781307         JBP      SRID        3A        54   
3  2023-10-03 22:13:07.781307         JBP      SRID        SL        54   
4  2023-10-03 22:13:07.781307         JBP       KKB        1A        69   

   duration  
0      33.0  
1      33.0  
2      33.0  
3      33.0  
4      49.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326643 entries, 0 to 326642
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   baseFare           326643 non-null  int64  
 1   reservationCharge  326643 non-null  int64  
 2   superfastCharge    326643 non-null  int64  
 3   fuelAmount         326643 non-null  float64
 4   totalConcession    326643 non-null  int64  
 5   tatkalFare         326643 non-null  int64  
 6   serviceTax         326643 non-null  float64
 7   otherCharge        326643 non-null  int64  
 8   cateringCharge     326643 non-null  int64  
 9   dynamicFare        326643 non-null  int64  
 10  totalFare          326643 non-null  int64  
 11  availability       326643 non-null  object 
 12  trainNumber        326643 non-null  int64  
 13  timeStamp          326643 non-null  object 
 14  fromStnCode        326643 non-null  object 
 15  toStnCode          326643 non-null  object 
 16  cl

In [26]:
df.describe()

baseFare  reservationCharge  superfastCharge  fuelAmount  \
count  326643.000000      326643.000000    326643.000000    326643.0   
mean      890.075122          38.157805        20.058091         0.0   
std       793.765711          14.324952        24.646072         0.0   
min        30.000000          15.000000         0.000000         0.0   
25%       362.000000          20.000000         0.000000         0.0   
50%       626.000000          40.000000         0.000000         0.0   
75%      1222.000000          50.000000        45.000000         0.0   
max      6541.000000          60.000000        75.000000         0.0   

       totalConcession  tatkalFare     serviceTax    otherCharge  \
count         326643.0    326643.0  326643.000000  326643.000000   
mean               0.0         0.0      42.761510       0.053208   
std                0.0         0.0      45.080793       1.018403   
min                0.0         0.0       0.000000       0.000000   
25%                0.0         0.0       0.000000       0.000000   
50%                0.0         0.0      34.000000       0.000000   
75%                0.0         0.0      65.000000       0.000000   
max                0.0         0.0     334.000000      25.000000   

       cateringCharge    dynamicFare      totalFare    trainNumber  \
count   326643.000000  326643.000000  326643.000000  326643.000000   
mean         4.990601       4.224771    1000.355281   14597.751870   
std         42.586032      49.050982     872.003147    4734.686291   
min          0.000000       0.000000      45.000000    1027.000000   
25%          0.000000       0.000000     395.000000   12316.000000   
50%          0.000000       0.000000     710.000000   13020.000000   
75%          0.000000       0.000000    1370.000000   18477.000000   
max       1365.000000    1518.000000    8375.000000   22645.000000   

            distance       duration  
count  326643.000000  326643.000000  
mean      587.745153     644.124564  
std       548.858324     581.665800  
min         1.000000   -1423.000000  
25%       164.000000     193.000000  
50%       404.000000     462.000000  
75%       861.000000     936.000000  
max      3149.000000    3225.000000

In [27]:
df.shape

(326643, 19)

In [28]:
df.isnull().sum()

baseFare             0
reservationCharge    0
superfastCharge      0
fuelAmount           0
totalConcession      0
tatkalFare           0
serviceTax           0
otherCharge          0
cateringCharge       0
dynamicFare          0
totalFare            0
availability         0
trainNumber          0
timeStamp            0
fromStnCode          0
toStnCode            0
classCode            0
distance             0
duration             0
dtype: int64

In [11]:
for columns in df:
    print([columns,":",df[columns].nunique()])


['baseFare', ':', 1840]
['reservationCharge', ':', 5]
['superfastCharge', ':', 5]
['fuelAmount', ':', 1]
['totalConcession', ':', 1]
['tatkalFare', ':', 1]
['serviceTax', ':', 276]
['otherCharge', ':', 3]
['cateringCharge', ':', 69]
['dynamicFare', ':', 475]
['totalFare', ':', 976]
['availability', ':', 27639]
['trainNumber', ':', 533]
['timeStamp', ':', 579]
['fromStnCode', ':', 1480]
['toStnCode', ':', 1594]
['classCode', ':', 6]
['distance', ':', 2759]
['duration', ':', 2912]


In [12]:
 # their three columns which has 1 value so they are not get any impact on the data
df2=df.drop(['fuelAmount','totalConcession','tatkalFare'],axis=1)

In [13]:
df.shape

(326643, 19)

In [14]:
df2.dtypes

baseFare               int64
reservationCharge      int64
superfastCharge        int64
serviceTax           float64
otherCharge            int64
cateringCharge         int64
dynamicFare            int64
totalFare              int64
availability          object
trainNumber            int64
timeStamp             object
fromStnCode           object
toStnCode             object
classCode             object
distance               int64
duration             float64
dtype: object

In [15]:
df2.head()

baseFare  reservationCharge  superfastCharge  serviceTax  otherCharge  \
0      1059                 60                0        56.0            0   
1       626                 50                0        34.0            0   
2       441                 40                0        24.0            0   
3       125                 20                0         0.0            0   
4      1059                 60                0        56.0            0   

   cateringCharge  dynamicFare  totalFare  \
0               0            0       1175   
1               0            0        710   
2               0            0        505   
3               0            0        145   
4               0            0       1175   

                                        availability  trainNumber  \
0  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   
1  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   
2  [{'date': '2-12-2023', 'status': 'AVAILABLE-01...        11464   
3  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   
4  [{'date': '2-12-2023', 'status': 'AVAILABLE-00...        11464   

                    timeStamp fromStnCode toStnCode classCode  distance  \
0  2023-10-03 22:13:07.781307         JBP      SRID        1A        54   
1  2023-10-03 22:13:07.781307         JBP      SRID        2A        54   
2  2023-10-03 22:13:07.781307         JBP      SRID        3A        54   
3  2023-10-03 22:13:07.781307         JBP      SRID        SL        54   
4  2023-10-03 22:13:07.781307         JBP       KKB        1A        69   

   duration  
0      33.0  
1      33.0  
2      33.0  
3      33.0  
4      49.0

In [16]:
for columns in df2:
    print([columns,":",df2[columns].nunique()])

['baseFare', ':', 1840]
['reservationCharge', ':', 5]
['superfastCharge', ':', 5]
['serviceTax', ':', 276]
['otherCharge', ':', 3]
['cateringCharge', ':', 69]
['dynamicFare', ':', 475]
['totalFare', ':', 976]
['availability', ':', 27639]
['trainNumber', ':', 533]
['timeStamp', ':', 579]
['fromStnCode', ':', 1480]
['toStnCode', ':', 1594]
['classCode', ':', 6]
['distance', ':', 2759]
['duration', ':', 2912]


In [19]:
print(df2['otherCharge'].unique())
print(df2['reservationCharge'].unique())
print(df2['superfastCharge'].unique())
print(df2['classCode'].unique())

[ 0 25 15]
[60 50 40 20 15]
[ 0 45 30 15 75]
['1A' '2A' '3A' 'SL' '2S' 'CC']


In [20]:
#reservation charge depends on the classcode
df_res = df2.groupby(['classCode', 'reservationCharge'])['totalFare'].count()

In [22]:
df_res.head()

classCode  reservationCharge
1A         20                     388
           60                   36763
2A         50                   83630
           60                     389
2S         15                    9398
Name: totalFare, dtype: int64

In [24]:
 #Superfast charge only depends on (trainNumber, classCode) pair
df_sup = df2.groupby(['trainNumber','classCode', 'superfastCharge'])['totalFare'].count()

In [26]:
df_sup

trainNumber  classCode  superfastCharge
1027         2A         0                  100
             3A         0                  100
             SL         0                  100
1065         2S         0                   75
             CC         0                   75
                                          ... 
22644        3A         45                 455
             SL         30                 455
22645        2A         45                 272
             3A         45                 272
             SL         30                 272
Name: totalFare, Length: 1607, dtype: int64

In [27]:
df2.columns

Index(['baseFare', 'reservationCharge', 'superfastCharge', 'serviceTax',
       'otherCharge', 'cateringCharge', 'dynamicFare', 'totalFare',
       'availability', 'trainNumber', 'timeStamp', 'fromStnCode', 'toStnCode',
       'classCode', 'distance', 'duration'],
      dtype='object')

In [28]:
# Adding independent columns to indicate if the train has catering or dynamic charges. Though we are losing some
# information but it is for model simplification
df2['if_offering_catering'] = df.cateringCharge>0
df2['if_dynamic_fare'] = df.dynamicFare>0

In [29]:
df2.columns

Index(['baseFare', 'reservationCharge', 'superfastCharge', 'serviceTax',
       'otherCharge', 'cateringCharge', 'dynamicFare', 'totalFare',
       'availability', 'trainNumber', 'timeStamp', 'fromStnCode', 'toStnCode',
       'classCode', 'distance', 'duration', 'if_offering_catering',
       'if_dynamic_fare'],
      dtype='object')